### ISSUE TITLE
feedback

### ISSUE THREAD

**Issue by thunder-red-star** [ThePotatoPowers/ScheduleComparison#1]
it definitely works

feature ideas:
* writing in each course id, section, and room is pretty annoying. maybe you could implement some way we could just copy paste the entire block from Talos and parse that data?
* ui needs work (on mobile, submit data needs to be scrolled horizontally but is fine, compare data is unusable)
![image](https://user-images.githubusercontent.com/67127399/213839722-93bbf37e-4a97-4b36-b76d-db1ea36ca54f.png)
* otherwise it's fine

**Comment by achen318** [comment]
lgtm!

**Comment by zidanekarim** [comment]
Copy pasting data is too vulnerable to incorrect information and leads to more issues. I tried implementing this, but Talos REALLY does not make it easy to copy paste since I have to separate the course name, which is pretty useless to me
